#!/usr/bin/env tsx
/**
 * format-licenses.ts — read the JSON output of `pnpm licenses list
 * --json --prod` from stdin (or a file) and write
 * `docs/THIRD_PARTY.md` as a sorted, grouped, Markdown inventory.
 *
 * Usage:
 *   pnpm licenses list --json --prod \
 *     | tsx scripts/format-licenses.ts > docs/THIRD_PARTY.md
 *
 * Why pnpm's built-in vs license-checker: pnpm walks the workspace
 * graph natively and dedupes by license, which is exactly the shape
 * we want for a reviewer-readable inventory.
 */

import { readFileSync } from 'node:fs';

interface PnpmLicenseEntry {
  name: string;
  versions: string[];
  license: string;
  author?: string;
  homepage?: string;
  description?: string;
}

type PnpmLicensesJson = Record<string, PnpmLicenseEntry[]>;

const FORBIDDEN = ['GPL-2.0', 'GPL-3.0', 'AGPL-3.0', 'AGPL-1.0', 'SSPL-1.0'];

function isForbidden(license: string): boolean {
  const up = license.toUpperCase();
  return FORBIDDEN.some((f) => up.includes(f) && !up.includes('LGPL'));
}

function main(): void {
  const input = process.argv[2] ? readFileSync(process.argv[2], 'utf8') : readFileSync(0, 'utf8');

  const parsed = JSON.parse(input) as PnpmLicensesJson;

  // Drop the local workspace package itself.
  delete parsed.UNLICENSED;

  const licenses = Object.keys(parsed).sort((a, b) => {
    const score = (l: string): number => {
      if (l === 'Unknown' || l === 'UNKNOWN') return 99;
      if (isForbidden(l)) return 50;
      return 10;
    };
    const sa = score(a);
    const sb = score(b);
    return sa === sb ? a.localeCompare(b) : sa - sb;
  });

  const totalPackages = licenses.reduce((acc, l) => acc + (parsed[l]?.length ?? 0), 0);

  const violations: { name: string; versions: string[]; license: string }[] = [];
  for (const license of licenses) {
    if (!isForbidden(license)) continue;
    for (const pkg of parsed[license] ?? []) {
      violations.push({
        name: pkg.name,
        versions: pkg.versions,
        license: pkg.license,
      });
    }
  }

  const log = (s: string): void => {
    // eslint-disable-next-line no-console
    console.log(s);
  };

  log('# Third-Party Licenses');
  log('');
  log(
    '> Auto-generated by `pnpm licenses list --json --prod | ' +
      'tsx scripts/format-licenses.ts > docs/THIRD_PARTY.md`. Do not ' +
      'edit by hand; re-run when dependencies change.',
  );
  log('');
  log(`Total production packages: **${totalPackages}**`);
  log(`Distinct licenses: **${licenses.length}**`);
  log('');

  if (violations.length > 0) {
    log('> ⚠️  **Copyleft license violation:** the following packages');
    log('> are licensed under a license incompatible with the MIT-licensed');
    log('> primary artifact. Remove or replace them before release.');
    log('');
    for (const v of violations) {
      log(`> - ${v.name}@${v.versions.join(', ')} — ${v.license}`);
    }
    log('');
  } else {
    log('No copyleft (GPL/AGPL/SSPL) licenses detected. ✅');
    log('');
  }

  log('## Summary');
  log('');
  log('| License | Count |');
  log('| ------- | ----- |');
  for (const license of licenses) {
    log(`| ${license} | ${(parsed[license] ?? []).length} |`);
  }
  log('');

  for (const license of licenses) {
    const bucket = (parsed[license] ?? []).slice().sort((a, b) => a.name.localeCompare(b.name));
    log(`## ${license} (${bucket.length})`);
    log('');
    log('| Package | Versions | Homepage |');
    log('| ------- | -------- | -------- |');
    for (const row of bucket) {
      const homepage = row.homepage ? `<${row.homepage}>` : '—';
      log(`| \`${row.name}\` | ${row.versions.join(', ')} | ${homepage} |`);
    }
    log('');
  }

  if (violations.length > 0) {
    process.exit(1);
  }
}

main();
